from __future__ import annotations

GITHUB_PROFILE   = "https://github.com/hndrapratamaa"
GITHUB_REPO      = "https://github.com/hndrapratamaa/voidclip"
GITHUB_ISSUES    = "https://github.com/hndrapratamaa/voidclip/issues"
PAYPAL_DONATE    = "https://paypal.me/hndrapratamaa"

APP_JUDUL        = "Voidclip.mov"
APP_TAGLINE      = "Ngedit video kagak ribet, cuy!"

BTN_SIKAT        = "Sikat!"
BTN_BUNGKUS      = "Bungkus"
BTN_BALIK        = "Balik"
BTN_SEGERIN      = "Segerin"
BTN_STOP         = "Stop Bos"
BTN_JEDA         = "Jeda Dulu"
BTN_LANJUT       = "Lanjut Gas"
BTN_MULAI        = "Mulai Cuy"
BTN_TAMBAH       = "Tambah Bro"
BTN_HAPUS        = "Hapus Aja"
BTN_PILIH        = "Pilih Bos"
BTN_SIMPAN       = "Simpen"
BTN_BATAL        = "Gausah"
BTN_DONATE       = "Traktir Bos"
BTN_GITHUB       = "Cek Repo"

LBL_INPUT        = "File Masuk"
LBL_OUTPUT       = "Hasil Jadi"
LBL_PRESET       = "Mode Render"
LBL_SUBTITLE     = "Subtitle Gimana"
LBL_PROGRESS     = "Proses..."
LBL_ANTRIAN      = "Antrian Job"
LBL_STATUS       = "Status Bos"
LBL_LOG          = "Log Bocor"
LBL_DESKRIPSI    = "Deskripsi & Hashtag"
LBL_NOTEPAD      = "Coret-coretan"

JUDUL_AUTO_UP    = "Auto Upload — Aciona"
LBL_START_SCRIPT = "Start Script"
LBL_PAUSE_SCRIPT = "Jeda Script"
LBL_STOP_SCRIPT  = "Berhentiin"
LBL_NOTEPAD_MINI = "Deskripsi / Hashtag"

MSG_IDLE         = "Santai dulu bos, belum ada kerjaan."
MSG_MULAI_PROSES = "Gas bos! Lagi diproses nih..."
MSG_JEDA         = "Dijeda dulu, nanti dilanjut ya bos."
MSG_LANJUT       = "Lanjut gaspol bos!"
MSG_SELESAI      = "Kelar blay! Semua udah beres."
MSG_GAGAL        = "Gagal blay! Ada yang error nih."
MSG_DIBATAL      = "Dibatalin bos, santai."
MSG_ANTRIAN_KOSONG = "Antrian kosong bos, masukin dulu donk."
MSG_TAMBAH_JOB   = "Job baru masuk, gas!"
MSG_HAPUS_JOB    = "Job dihapus bos."

LOG_SCAN_FOLDER  = "Nyari file episode di folder: {}"
LOG_TOTAL_PART   = "Ketemu {} part bro, langsung gas!"
LOG_MULAI_PART   = "Mulai upload Part {} dari {} bos..."
LOG_KLIK_UP      = "Klik tombol Upload bos..."
LOG_PILIH_VID    = "Milih file video: {}"
LOG_CONFIRM_VID  = "Konfirmasi video dipilih bos."
LOG_ISI_DESK     = "Ngisi deskripsi & hashtag..."
LOG_SCROLL       = "Scroll dikit ke bawah..."
LOG_PILIH_PLAYLIST = "Milih playlist bos..."
LOG_KLIK_POST    = "Klik Post bos!"
LOG_POST_NOW     = "Klik Post Now, tunggu sebentar..."
LOG_UPLOAD_TUNGGU = "Tunggu upload kelar, sekitar 5 menit bos..."
LOG_PART_BERES   = "Part {} kelar di-upload, mantap!"
LOG_SEMUA_BERES  = "Semua part udah kelar, gokil blay!"
LOG_BERSIHIN     = "Lagi bersihin file video yang udah keupload..."
LOG_FILE_DIHAPUS = "File dihapus: {}"
LOG_BERSIHIN_KELAR = "Bersihin udah kelar, storage lega bos!"
LOG_DIJEDA       = "Script dijeda bos, sabar ya..."
LOG_DILANJUT     = "Script dilanjut, gas bos!"
LOG_DISTOP       = "Script distop paksa bos."
LOG_ERROR        = "Eror bos: {}"

JUDUL_WINDOW_MINI = "Aciona — Floating"
TOOLTIP_START    = "Mulai sekuens otomatisasi upload"
TOOLTIP_PAUSE    = "Jeda / lanjutin script"
TOOLTIP_STOP     = "Stop paksa script"
TOOLTIP_NOTEPAD  = "Tulis deskripsi & hashtag di sini"

ERR_FOLDER_KOSONG = "Folder episode kosong blay, masukin dulu!"
ERR_PART_GAK_KETEMU = "Gak ada file Part XXX di folder ini bos."
ERR_PYAUTOGUI    = "pyautogui belum keinstal bos, install dulu: pip install pyautogui"
ERR_KONEKSI      = "Koneksi error blay, cek internet dulu!"
